fixtures:
    forge_modules:
        concat:
            # Lock at 2.2.1 for Puppet 3
            repo: 'puppetlabs/concat'
            ref: '2.2.1'
        stdlib:
            # Lock at 4.13.0 for Puppet 3
            repo: 'puppetlabs/stdlib'
            ref: '4.13.0'
    symlinks:
        certs: "#{source_dir}"
