fixtures:
    symlinks:
      certs: "#{source_dir}"
    repositories:
      stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
